//! Free-function helpers for agnova: system file generation utilities.

use uuid::Uuid;

use super::types::{Filesystem, PartitionSpec, SecurityConfig};

/// Generate a random machine-id suitable for `/etc/machine-id`.
pub fn generate_machine_id() -> String {
    Uuid::new_v4().to_string().replace('-', "")
}

/// Generate `/etc/hostname` content.
pub fn generate_hostname_config(hostname: &str) -> String {
    format!("{}\n", hostname)
}

/// Generate a basic `/etc/fstab` from the partition specifications.
pub fn generate_fstab(partitions: &[PartitionSpec], encrypt: bool) -> String {
    let mut lines = vec![
        "# /etc/fstab — generated by agnova".to_string(),
        "# <device>  <mount>  <type>  <options>  <dump>  <pass>".to_string(),
    ];

    for part in partitions {
        let device = if encrypt && part.mount_point == "/" {
            "/dev/mapper/agnos-root".to_string()
        } else {
            format!("LABEL={}", part.label)
        };

        let options = if part.filesystem == Filesystem::Swap {
            "sw"
        } else if part.mount_point == "/" {
            "defaults,errors=remount-ro"
        } else {
            "defaults"
        };

        let pass = if part.mount_point == "/" {
            "1"
        } else if part.filesystem == Filesystem::Swap || part.filesystem == Filesystem::Vfat {
            "0"
        } else {
            "2"
        };

        let mount = if part.filesystem == Filesystem::Swap {
            "none"
        } else {
            &part.mount_point
        };

        lines.push(format!(
            "{}  {}  {}  {}  0  {}",
            device, mount, part.filesystem, options, pass
        ));
    }

    lines.join("\n") + "\n"
}

/// Default kernel command-line parameters based on security settings.
pub fn default_kernel_params(security: &SecurityConfig) -> Vec<String> {
    let mut params = vec!["quiet".to_string(), "loglevel=3".to_string()];

    if security.enable_luks {
        params.push("rd.luks=1".to_string());
    }
    if security.enable_secureboot {
        params.push("lockdown=integrity".to_string());
    }
    if security.enable_tpm {
        params.push("tpm_tis.interrupts=0".to_string());
    }
    if security.enable_dmverity {
        params.push("dm_verity.verify=1".to_string());
    }

    // LSM stack
    params.push("lsm=landlock,lockdown,yama,apparmor,bpf".to_string());

    params
}
